drop table if exists menu_items;
drop table if exists menu_categories;

create table menu_items
(
    itemid INT GENERATED BY DEFAULT AS IDENTITY,
    title varchar,
	description varchar,
	price int,
	allergens varchar,
	status varchar 
);

create table menu_categories
(
	categoryId INT GENERATED BY DEFAULT AS IDENTITY,
	title varchar,
	description varchar
);

insert into menu_items(title, description, price, allergens, status)
values('Pizza Margherita', 'Everyone knows and loves it – pizza margherita is a universally praised pizza for a reason. Originating in Naples, the margherita pizza has an interesting history supposedly rooted in a visit by Queen Margherita to Naples. The iconic pizza margherita is also known for representing the colours of the Italian flag: red tomato sauce, white mozzarella, and green basil. The combination of these ingredients creates a delicious pizza which has withstood the test of time',
	  6.80, 'A,B,C', 'available');  
	  
insert into menu_items(itemid, title, description, price, allergens, status)
values(2, 'Marinara', 'Like the margherita pizza, pizza marinara also originated in Naples. This simple pizza is topped with plain marinara sauce, oregano and garlic. Essentially, it is very similar to the margherita pizza but lacks the cheese and basil. Apparently, back in the 1700s and 1800s, pizza marinara was popular with poor sailors and made on their ships as the ingredients used to make it were easily preserved.',
	  7.80, 'A,B,C,C,E,F', 'available');  
	  
	  
	  select * from menu_items;