-- DB Name: GuestViewFreebi

drop table if exists orderedItems;
drop table if exists menu_itemsXmenu_categories;
drop table if exists menu_items;
drop table if exists menu_categories;
drop table if exists reviews;
drop table if exists orders;

create table menu_items
(
    itemid INT GENERATED BY DEFAULT AS IDENTITY primary key,
    title varchar,
	description varchar,
	price float,
	allergens varchar,
	status varchar 
);

create table menu_categories
(
	categoryId INT GENERATED BY DEFAULT AS IDENTITY primary key,
	title varchar,
	description varchar
);

create table menu_itemsXmenu_categories
(
	itemId int,
	categoryId int,
	CONSTRAINT fk_itemId
      FOREIGN KEY(itemId) 
	  REFERENCES menu_items(itemid),
	CONSTRAINT fk_categoryId
      FOREIGN KEY(categoryId) 
	  REFERENCES menu_categories(categoryId)
);

create table reviews
(
	reviewId INT GENERATED BY DEFAULT AS IDENTITY primary key,
	description varchar,
	stars int,
	createdAt date
);

create table orders
(
	orderId INT GENERATED BY DEFAULT AS IDENTITY primary key,
	status VARCHAR,
	orderDate DATE,
	tableId INT,
	paymentReference VARCHAR,
	paymentToken VARCHAR,
	totalAmount FLOAT
);

create table orderedItems
(
	itemId int,
	orderId int,
	CONSTRAINT fk_itemId
      FOREIGN KEY(itemId) 
	  REFERENCES menu_items(itemid),
	CONSTRAINT fk_orderId
      FOREIGN KEY(orderId) 
	  REFERENCES orders(orderId)
);


	  
select * from menu_items;
select * from menu_categories;
select * from menu_items items, menu_categories cat, menu_itemsXmenu_categories merger
where items.itemId = merger.itemId and cat.categoryId = merger.categoryId;
select * from reviews;